# Generated by Django 3.0.5 on 2020-04-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
