# Generated by Django 3.0.5 on 2020-04-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200422_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offert',
            name='content',
        ),
        migrations.RemoveField(
            model_name='offert',
            name='title',
        ),
        migrations.AddField(
            model_name='offert',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='company_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offert',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='tech',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='offert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technology', to='api.Offert'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='tech',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='tech_lvl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
