# Generated by Django 3.0.5 on 2020-04-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200422_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offert',
            name='tech',
        ),
    ]
