# Generated by Django 3.0.5 on 2020-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_offert_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='tech',
            field=models.CharField(max_length=12),
        ),
    ]
