# Generated by Django 3.0.5 on 2020-04-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200422_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='offert',
            name='emp_type',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='exp_lvl',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='place_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='salary_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offert',
            name='salary_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offert',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offert',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offert',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=15)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=15)),
                ('offert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='api.Offert')),
            ],
        ),
    ]
