# Generated by Django 3.0.5 on 2020-04-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200422_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='offert',
        ),
    ]
