# Generated by Django 3.0.5 on 2020-04-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_location_offert'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='offert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='api.Offert'),
        ),
    ]
