# Generated by Django 3.0.5 on 2020-04-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_location_offert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='offert',
        ),
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loation', to='api.Location'),
        ),
    ]
