# Generated by Django 3.0.5 on 2020-04-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200423_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='offert',
            name='offer_title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='offert',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerts', to='api.Location'),
        ),
    ]
