# Generated by Django 3.0.5 on 2020-05-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200425_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='offert',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offert',
            name='description',
            field=models.TextField(default='<p>elo</p>'),
        ),
        migrations.AddField(
            model_name='offert',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
