# Generated by Django 3.0.5 on 2020-05-21 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200501_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offert',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offert',
            name='description',
            field=models.TextField(blank=True, default='<p>elo</p>', null=True),
        ),
        migrations.AlterField(
            model_name='offert',
            name='emp_type',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='offert',
            name='exp_lvl',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='offert',
            name='image',
            field=models.ImageField(default='0.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='offert',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerts', to='api.Location'),
        ),
        migrations.AlterField(
            model_name='offert',
            name='offer_title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='offert',
            name='place_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offert',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='offert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology', to='api.Offert'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='tech',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tech',
            name='tech_lvl',
            field=models.CharField(max_length=100),
        ),
    ]
