# Generated by Django 3.0.5 on 2020-05-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200522_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='image',
            field=models.ImageField(default='9.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='offert',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
